image: docker:18.09.7-dind

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

build_job:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t "$CI_REGISTRY_USER"/reddit:$CI_COMMIT_SHA ./docker-monolith
    - docker push "$CI_REGISTRY_USER"/reddit:$CI_COMMIT_SHA

test_unit_job:
  before_script:
    - cd reddit
    - bundle install
  stage: test
  image: ruby:2.4.2
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  before_script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD"
    - apk --update --no-cache bash
    - docker kill reddit || true
  script:
    - docker pull "$CI_REGISTRY_USER"/reddit:$CI_COMMIT_SHA
    - docker run --name reddit -d -p 9292:9292 --rm "$CI_REGISTRY_USER"/reddit:$CI_COMMIT_SHA
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
