stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - apk --update --no-cache add py-pip docker build-base python2-dev
  - pip install docker-compose
  - cd src

build_job:
  stage: build
  script:
    - docker-compose down
    - docker-compose build

test_unit_job:
  before_script:
    - cd reddit
    - bundle install
  stage: test
  image: ruby:2.4.2
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - docker-compose up -d
  environment:
    name: dev
    url: http://dev.example.com 

branch review:
  stage: review
  script: 
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker-compose up -d
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
    - docker-compose up -d
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
    - docker-compose up -d
  environment:
    name: production
    url: https://example.com
