version: '3.3'
services:
  mongo_db:
    image: mongo:${TAG_M}
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${TAG}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front-net
  post:
    image: ${USERNAME}/post:${TAG}
    networks:
      - back-net
      - front-net
  comment:
    image: ${USERNAME}/comment:${TAG}
    networks:
      - back-net
      - front-net

volumes:
  post_db:

networks:
  back-net:
  front-net:
